### ISSUE TITLE
Stale feature branches

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/reflection_based_radar_object_model#5]
There are three open but stale feature branches. Some of which seem to have been already merged previously.
@LukasElster and @PhRosenberger can you check, if these branches are still relevant?

**Comment by PhRosenberger** [comment]
I guess they are all 3 outdated.
Especially the output-strategy branch seems obsolete, as there are output strategies in the main branch.
@LukasElster what do you think?

**Comment by LukasElster** [comment]
Yes, they are outdated. We can delete them and clean up the repo.

**Comment by ClemensLinnhoff** [comment]
Thank you for your responses. Then I will delete the branches.
